language: php
os: linux

cache:
  directories:
  - $HOME/.composer/cache

env:
  global:
  - setup=basic
  - coverage=false

branches:
  except:
  - /analysis-.*/

before_install:
- if [[ $coverage = 'false' ]]; then phpenv config-rm xdebug.ini || true; fi

install:
- if [[ $setup = 'basic'  ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi
- if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

script:
- if [[ $coverage = 'true' ]]; then composer test-cover; else composer test; fi

after_success:
- if [[ $coverage = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi

jobs:
  include:
  - php: 7.0
  - php: 7.0
    env: setup=lowest

  - php: 7.1
  - php: 7.1
    env: setup=lowest

  - php: 7.2
  - php: 7.2
    env: setup=lowest

  - php: 7.3
  - php: 7.3
    env: setup=lowest coverage=true

  - php: 7.4
  - php: 7.4
    env: setup=lowest
